### ISSUE TITLE
トップページの画像を差し替える

### ISSUE THREAD

**Issue by deraru** [huapay/huapay.github.io#10]
サンプル画像を後ほどお渡しする正式な画像に差し替えてください。

**Comment by mie94** [comment]
![home](https://user-images.githubusercontent.com/36589900/48238777-8e6dc100-e40f-11e8-8bd0-d1e5af15dfe4.jpg)
![home](https://user-images.githubusercontent.com/36589900/48238778-90378480-e40f-11e8-9da6-c39fddb4c97c.jpg)
![home](https://user-images.githubusercontent.com/36589900/48238781-9168b180-e40f-11e8-80b6-88ae79403c9d.jpg)
![home](https://user-images.githubusercontent.com/36589900/48238783-93cb0b80-e40f-11e8-8a6c-ccacf5551095.jpg)
[ワイヤフレーム（HOMEv2）.pdf](https://github.com/huapay/huapay.github.io/files/2564327/HOMEv2.pdf)
[アイコンのURL.txt](https://github.com/huapay/huapay.github.io/files/2564330/URL.txt)

@ItinoseSan 画像の差し替えをお願いします。参考としてワイヤフレームも更新しました。全体的に画像を使いすぎった気がしたので、下の「サービス」の部分はアイコンに修正してください。よろしくお願いします。

**Comment by ItinoseSan** [comment]
差し替えの方が終わったのでクローズさせていただきます。
