### ISSUE TITLE
トップページを作る

### ISSUE THREAD

**Issue by deraru** [huapay/huapay.github.io#3]
後ほどワイヤーを添付します

**Comment by deraru** [comment]
@ItinoseSan こんな感じでお願いします。
画像は後ほどお渡しするので、開発時はダミー画像で代替してください。
デザインはこの通りに実装しなくて大丈夫です！
[ワイヤフレーム.pdf](https://github.com/huapay/huapay.github.io/files/2535541/default.pdf)

**Comment by mie94** [comment]
「中国人観光客はなぜ日本で「爆買い」をする？」の枠の色と背景色は #5 のカラーコードの色をつかってください。
