### ISSUE TITLE
越境EC決済支援ページを作る

### ISSUE THREAD

**Issue by deraru** [huapay/huapay.github.io#7]
ワイヤーは後ほど添付します。

**Comment by mie94** [comment]
- 越境ECのワイヤーフレームです。
[ワイヤフレーム（越境EC）.pdf](https://github.com/huapay/huapay.github.io/files/2594854/EC.pdf)
![1](https://user-images.githubusercontent.com/36589900/48701692-6dd51080-ec32-11e8-8fd0-e492a71a9592.jpg)
![china_image02](https://user-images.githubusercontent.com/36589900/48701694-70d00100-ec32-11e8-96d0-fb280f531663.png)
![2](https://user-images.githubusercontent.com/36589900/48701756-93621a00-ec32-11e8-9c60-f715583987b2.png)
![5](https://user-images.githubusercontent.com/36589900/48701777-9e1caf00-ec32-11e8-9cdc-0568ddbe2c34.png)
![3](https://user-images.githubusercontent.com/36589900/48701793-a674ea00-ec32-11e8-9ec5-3669e1d1c54a.jpg)
![4](https://user-images.githubusercontent.com/36589900/48701798-a8d74400-ec32-11e8-91ef-734f5ec2f908.png)
